name: Flutter CI

on:
  push:
    branch:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: git pull git@github.com:Startupreneur-Application-Builder/basic_app.git