name: Flutter CI

on:
  push:
    branch:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: Startupreneur-Application-Builder/basic_app
        token: ${{ secrets.MY_REPO_SECRET || github.token }}
        fetch-depth: 0
    - run: | 
        git config --global user.email "subramanyarao4@gmail.com"
        git config --global user.name "imcoffeefreak"
        git remote add upstream https://github.com/Startupreneur-Application-Builder/basic_app.git
        git remote add origin https://github.com/Startupreneur-Application-Builder/testrepo.git
        git checkout -b new
        git pull --allow-unrelated-histories upstream master
        git add .
        git commit -m "Udpated"
        git push origin new