name: Flutter CI

on:
  push:
    branch:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: | 
    git config --global user.email "subramanyarao4@gmail.com"
    git config --global user.name "imcoffeefreak"
    git pull --allow-unrelated-histories https://github.com/Startupreneur-Application-Builder/basic_app.git